### ISSUE TITLE
5.1.0 not working.

### ISSUE THREAD

**Issue by bestpika** [requestly/requestly-issues#24]
Chrome 64.0.3282.39 with 5.1.0 (12/30) `replace host` and `redirect request` not working.

Console
![image](https://user-images.githubusercontent.com/5698157/34459217-9c690c24-ee24-11e7-99d0-f9f29bf242bd.png)

And https://www.requestly.in/library get 404.

**Comment by sachinjain024** [comment]
Thanks for logging the issue. We are looking into it. We will let you know
once the issue is fixed.

**Comment by sachinjain024** [comment]
@bestpika We have fixed the library issue and now you can use library. We are still looking into the queue full error.

**Comment by sachinjain024** [comment]
@bestpika We have fixed this issue and released v5.1.1. This should be available to you in an hour or so as soon as the build is published on chrome store. Thanks again for reporting.

**Comment by sachinjain024** [comment]
@bestpika Let me know if we can close this issue. cc: @requestly/requestly-extension-developers

**Comment by bestpika** [comment]
I update to 5.1.1, but sometime `replace host` and `redirect request` still not working.
I open console but see no error.

**Comment by bestpika** [comment]
I try to delete all rules and import, then work.
But when I close browser and open it, it not work again.

**Comment by sachinjain024** [comment]
@bestpika Can you give me an example which one does not work so that I can look into it ?
Is it possible for you to share your rules on requestly.extension@gmail.com and then I will have a look at what may be the possible issue.

**Comment by bestpika** [comment]
My rule.
[requestly.txt](https://github.com/requestly/requestly-issues/files/1595785/requestly.txt)

**Comment by bestpika** [comment]
I see a field `status`, but in requestly I can't set this.

**Comment by bestpika** [comment]
I see a field `status` in `pairs`, but in requestly I can't set this.

**Comment by sachinjain024** [comment]
@bestpika Thanks! We will test this out. We initially planned to use `status`  inside pairs as well but we never used that. We no longer use this field.

**Comment by harrysingh** [comment]
I also see similar issue where the redirect rules are not working. Unfortunately deleting the rules and importing back also does not work for me.

**Comment by sachinjain024** [comment]
Thanks @bestpika and @harrysingh for logging the issue. I have fixed the issue and deployed as version v5.1.2. It should be available in chrome store soon and then you can test if this issue is fixed or not.

**Comment by sachinjain024** [comment]
@bestpika Can we close this issue ?

**Comment by bestpika** [comment]
I tested, all okay!
